<?php

/**
 * @file modal_minimal_style.module
 * Proposition of alternative theming for CTools modals
 * Used everywhere when enabled, based on modal_minimal_style
 */

/**
 * Implement hook_init()
 */
function modal_mstyle_init() {
  // Do not load modal_minimal_style during the Drupal installation process, e.g. if part
  // of installation profiles.
  if (!drupal_installation_attempted()) {
    _modal_mstyle_doheader();
  }
}

/**
 * Loads the various js and css files.
 */
function _modal_mstyle_doheader() {
  static $already_added = FALSE;
  if ($already_added) {
    return; // Don't add the JavaScript and CSS multiple times.
  }
  $path = drupal_get_path('module', 'modal_mstyle');
  
  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');

  // Add CTools' javascript to the page.
  ctools_modal_add_js();
  
  // Image not found when not on a domain without subdirs
  // (e.g. when root path looks like http://mysite.com/dir/project-root/)
  // -> use drupal_add_js() & drupal_add_css() instead
  //$throbber = theme('image', array('path' => ctools_image_path('loading_animation.gif', 'modal_minimal_style'), 'alt' => t('Loading...'), 'title' => t('Loading')));
  $throbber = theme('image', array('path' => url($path .'/images/loading_animation.gif'), 'alt' => t('Loading...'), 'title' => t('Loading')));
  $js_settings = array(
    'modal-popup-minimal' => array(
      'modalSize' => array(
        'type' => variable_get('modal_minimal_type', 'scale'),
        'width' => floatval(variable_get('modal_minimal_width', 0.8)),
        'height' => floatval(variable_get('modal_minimal_height', 0.8)),
      ),
      'modalOptions' => array(
        'opacity' => floatval(variable_get('modal_forms_opacity', 0.85)),
        'background' => variable_get('modal_minimal_bg_color', '#000'),
      ),
      'animation' => 'fadeIn',
      'modalTheme' => 'modal_minimal_style',
      'throbber' => $throbber,
      'closeText' => t('Close'),
    ),
  );

  drupal_add_js($js_settings, 'setting');
  
  // Add modal_minimal_style own JavaScript and CSS.
  // Note : all these tests FAIL when not on a domain without subdirs
  // (e.g. when root path looks like http://mysite.com/dir/project-root/)
  // -> use drupal_add_js() & drupal_add_css() instead
  //$path = drupal_get_path('module','modal_mstyle');
  //$path = base_path() . drupal_get_path('module','modal_mstyle');
  //ctools_add_css('modal-minimal-style', 'modal_minimal_style');
  //ctools_add_js('modal-minimal-style', 'modal_minimal_style');
  //ctools_add_js('modal-minimal-style', 'modal_minimal_style',$path . '/js');
  //$path = drupal_get_path('module', 'modal_mstyle');
  drupal_add_js($path . '/js/modal-minimal-style.js');
  drupal_add_css($path . '/css/modal-minimal-style.css');
  
  $already_added = TRUE;
}

